# Generated by Django 5.1.3 on 2024-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ativo',
            field=models.FloatField(default=True),
        ),
    ]
