# Generated by Django 5.1.3 on 2024-11-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
