# Generated by Django 5.1.3 on 2024-11-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_combustivel',
            field=models.ManyToManyField(related_name='veiculos', to='veiculos.tipocombustivel'),
        ),
    ]
