# Generated by Django 5.1.3 on 2024-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_veiculo_tipo_combustivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
