# Generated by Django 5.1.3 on 2024-12-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('litros', models.TextField()),
                ('totais', models.TextField()),
            ],
            options={
                'ordering': ['-data_final'],
            },
        ),
    ]
