# Generated by Django 5.1.3 on 2024-12-04 13:14

import django.db.models.deletion
import django.utils.timezone
import postos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0003_veiculo_quilometragem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[postos.validators.cnpj_validator])),
                ('ativo', models.BooleanField(default=True)),
                ('tipos_combustivel', models.ManyToManyField(related_name='postos', to='veiculos.tipocombustivel')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField(default=0)),
                ('valor_litro', models.FloatField(default=0, validators=[postos.validators.preco_validator])),
                ('valor_total', models.FloatField(default=0, editable=False)),
                ('data_abastecimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastrado', models.DateTimeField(auto_now_add=True)),
                ('quilometragem', models.FloatField(default=0)),
                ('tipo_combustivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='veiculos.tipocombustivel')),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='veiculos.veiculo')),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abastecimentos', to='postos.posto')),
            ],
            options={
                'ordering': ['-data_cadastrado'],
            },
        ),
    ]
