# Generated by Django 5.1.3 on 2024-11-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
