# Generated by Django 5.1.3 on 2024-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimento',
            options={'ordering': ['-data_abastecimento']},
        ),
        migrations.RemoveField(
            model_name='abastecimento',
            name='data_cadastrado',
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='data_abastecimento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
