# Generated by Django 5.1.3 on 2024-12-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('postos', '0003_abastecimento_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimento',
            name='financeiro',
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='financeiro',
            field=models.ManyToManyField(related_name='abastecimentos', to='financeiro.financeiro'),
        ),
    ]
